version: "3.5"
services:
  fe:
    container_name: fe
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
  be:
    container_name: be
    build:
      context: ./server/node
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/node:/usr/src/app
    environment:
      - NODE_ENV=development
      - CONFIG=config.json
      - PRIVATE_KEY=${IRMA_PRIVATE_KEY}
      - FE_URL=http://fe:9000
      - REDIS_URL=redis://cache:6379
  cache:
    image: redis:alpine
    container_name: cache