version: '2'

services:
  # PROXYING IS NOW BEING DONE IN OVERLAY_PROXY

  # nginx:
  #   restart: always
  #   container_name: nginx_proxy
  #   image: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
  #     # - ./default.conf:/etc/nginx/conf.d/default.conf # override default conf, else in conflict with new conf
  #     - ./logs:/var/log/nginx
  #     - ./certs:/certs
  #     - ./domains:/domains
  #     # - ./test_page:/var/www # for debug purposes only
      
  node:
    restart: always
    container_name: voting_node
    build: "./voting_node"
    # CONTAINER ACCESABLE THROUGH NGINX REVERSED PROXY
    ports:
      - "8081:8000"
    environment:
      - development=0

  irma:
    restart: always
    container_name: irma_server
    build: "./irma_server"
    # CONTAINER ACCESABLE THROUGH NGINX REVERSED PROXY
    ports:
      - "8088:8088"
