version: "3.5"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./voting_node/
    environment:
      - NODE_ENV=production
      - CONFIG=config-dev.json
      - PRIVATE_KEY=${IRMA_PRIVATE_KEY}
      - POSTGRES_HOST=database
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hj21kjy
    ports:
      - "8000:8000"
    volumes:
      - ./voting_node/openstad:/openstad
      # - ./voting_node/server:/server
    depends_on:
      - database
      - irma_server

  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hj21kjy
    volumes:
     - ./dev/db/data:/var/lib/postgresql/data
    container_name: postgres

  irma_server:
    image: irmaservercontainer_irma
    ports:
      - "8088:8088"
    environment:
      # - BASE_URL=https://acc.attr.auth.amsterdam.nl
      - BASE_URL=http://b963f628.eu.ngrok.io
  
