version: "3.5"
services:
  fe:
    container_name: fe
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    ports:
      - "9000:9000"
  be:
    container_name: be
    build:
      context: ./server/node
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/node:/usr/src/app
    environment:
      - NODE_ENV=development
      - CONFIG=config.json
      - PRIVATE_KEY=${IRMA_PRIVATE_KEY}
    links:
      - fe:app
      # - irma-server
  # irma-server:
  #   container_name: irma-server
  #   image: di-irma-server_irma
  #   ports:
  #     - '8088:8088'
  #   environment:
  #     - BASE_URL=https://acc.attr.auth.amsterdam.nl
  # - BASE_URL=http://d3064d0d.eu.ngrok.io
