name: Client
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
defaults:
  run:
    working-directory: client
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test, build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn ${{ matrix.job }}
